apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: udgte6vwh-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/udgte6vwh-dotnet-basic